### ISSUE TITLE
Issue running the code

### ISSUE THREAD

**Issue by TianrenWang** [Octavian-ai/shortest-path#2]
I am trying to follow the run instruction on the readme but I keep getting the following error:
```
Franks-MacBook-Pro:shortest-path frank$ pipenv run ./train.sh
Creating a virtualenv for this project…
Pipfile: /Users/frank/Desktop/Natural Language Processing/shortest-path/Pipfile
Using /usr/local/bin/python3 (3.6.5) to create virtualenv…
⠹ Creating virtual environment...Using base prefix '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6'
Running virtualenv with interpreter /usr/local/bin/python3

✘ Failed creating virtual environment 
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.6/site-packages/pipenv/cli/command.py", line 408, in run
[pipenv.exceptions.VirtualenvCreationException]:       command=command, args=args, three=state.three, python=state.python, pypi_mirror=state.pypi_mirror
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 2310, in do_run
[pipenv.exceptions.VirtualenvCreationException]:       three=three, python=python, validate=False, pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 574, in ensure_project
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 506, in ensure_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 935, in do_create_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       extra=[crayons.blue("{0}".format(c.err)),]
[pipenv.exceptions.VirtualenvCreationException]: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/virtualenv.py", line 352, in copyfile
    os.symlink(srcpath, dest)
FileExistsError: [Errno 17] File exists: '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload' -> '/Users/frank/.local/share/virtualenvs/shortest-path-dfmXJRTK/lib/python3.6/lib-dynload'
```
To run this I just deleted everything related to Anaconda and brew re-installed python3.6.5, but I still keep getting this error. Would love some help.

**Comment by TianrenWang** [comment]
Never mind, I had to delete the existing folder to make it work.
